language: node_js

addons:
  sonarcloud:
    organization: "sogame-github"

install:
  - npm ci --quiet
  - npm run build
  - npm install -g danger-plugin-dangerfile-builder@0.1.1-beta.0
  - npm link danger-plugin-dangerfile-builder

script:
  - npm run danger
  - npm run lint
  - npm run test:coverage
  - sonar-scanner # SonarCloud
