language: node_js

addons:
  sonarcloud:
    organization: "sogame-github"

install:
  - npm ci --quiet
  - npm install -g danger-plugin-dangerfile-builder@0.1.2-beta.1
  - npm link danger-plugin-dangerfile-builder # Link the global version of "danger-plugin-dangerfile-builder" into the local "node_modules/"

script:
  - npm run danger
  - npm run lint
  - npm run test:coverage
  - sonar-scanner # SonarCloud
